version: '3'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: bookapi
      MYSQL_USER: app
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  api:
    build: ./api
    container_name: laravel_api
    restart: always
    environment:
      DB_HOST: db
      DB_DATABASE: bookapi
      DB_USERNAME: app
      DB_PASSWORD: password
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8000:8000"

  client:
    build: ./client
    container_name: nuxt_client
    networks:
      - app-network
    depends_on:
      - api
    ports:
      - "3000:3000"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
    depends_on:
      - client
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge

