name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build API Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/api:latest ./path-to-api

      - name: Build Client Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/client:latest ./path-to-client

      - name: Push API image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/api:latest

      - name: Push Client image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/client:latest

